# Generated by Django 4.2.29 on 2026-03-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('original_lyrics', models.TextField()),
                ('translated_lyrics', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='savedtranslation',
            constraint=models.UniqueConstraint(fields=('track_name', 'artist_name'), name='unique_song_translation'),
        ),
    ]
